services:
  backend:
    build: ./backend
    container_name: jstack-backend
    ports:
      - "5100:5000"
      - "3306:3306"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env  
    depends_on:
      - mongo
    
  frontend:
    build: ./frontend
    container_name: jstack-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: jstack-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: